#!/usr/bin/env python

import time
import signal
import threading
from wifi_wizard_daemon import WifiWizardDaemon


stop_event = threading.Event()


def sigint_handler(signum, frame):
    stop_event.set()

signal.signal(signal.SIGINT, sigint_handler)


def main():
    wwd = WifiWizardDaemon()
    wwd.start()
    while not stop_event.is_set():
        time.sleep(0.01)


if __name__ == '__main__':
    main()
