#!/usr/bin/python

import bt_server

def bt_callback(client_sock, client_info):
    print client_info

def main():
    bts = bt_server.BasecampBluetoothServer(bt_callback,)
    bts.start()


if __name__ == '__main__':
    main()